### ISSUE TITLE
Aiohttp.get deprecated

### ISSUE THREAD

**Issue by Artimi** [textbook/aslack#12]
Hello,
I've encountered a problem with aslack and aiohttp. Aiohttp deprecated `aiohttp.get()` function https://github.com/aio-libs/aiohttp/issues/729 in version `0.21` which is used in aslack https://github.com/textbook/aslack/blob/master/aslack/slack_api.py#L192. Problem is that in setup.py the aiohttp is constrained only to be `>=0.15.0` https://github.com/textbook/aslack/blob/master/setup.py#L59 . I hotfixed this in production by pinning aiohttp to version `0.20.0`, because I don't use it anywhere else in the program. Please update `setup.py` or better update your code to be able to have recent `aiohttp`.

**Comment by textbook** [comment]
Thanks for letting me know; I'll push a quick fix to pin the dependency, then look into adopting the session approach, as it seems like that's going to be more efficient.

**Comment by textbook** [comment]
v0.11.0 pins the dependency: https://github.com/textbook/aslack/blob/v0.11.0/setup.py#L59

**Comment by Artimi** [comment]
Thanks for fast fix!
